testapp/config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  resources :vessels, except: :show

  namespace :admin do
    resources :vessels
  end

  root to: 'vessels#index'
end

testapp/app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

testapp/app/models/vessel.rb
class Vessel < ActiveRecord::Base
  validates :title, :description, :daily_price, :fee_pc, :presence => true
  validates :daily_price, :fee_pc, :numericality => true
end

testapp/app/controllers/admin/vessels_controller.rb
class Admin::VesselsController < ApplicationController
  before_action :authenticate_admin!
  layout 'admin'
  before_action :set_vessel, only: [:show, :edit, :update, :destroy]

  # GET /vessels
  # GET /vessels.json
  def index
    @vessels = Vessel.all
  end

  def show
  end

  # GET /vessels/new
  def new
    @vessel = Vessel.new
  end

  # GET /vessels/1/edit
  def edit
  end

  # POST /vessels
  # POST /vessels.json
  def create
    @vessel = Vessel.new(vessel_params)

    respond_to do |format|
      if @vessel.save
        format.html { redirect_to admin_vessels_url, notice: 'Vessel was successfully created.' }
        format.json { render :show, status: :created, location: @vessel }
      else
        format.html { render :new }
        format.json { render json: @vessel.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /vessels/1
  # PATCH/PUT /vessels/1.json
  def update
    respond_to do |format|
      if @vessel.update(vessel_params)
        format.html { redirect_to admin_vessels_url, notice: 'Vessel was successfully updated.' }
        format.json { render :show, status: :ok, location: @vessel }
      else
        format.html { render :edit }
        format.json { render json: @vessel.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /vessels/1
  # DELETE /vessels/1.json
  def destroy
    @vessel.destroy
    respond_to do |format|
      format.html { redirect_to admin_vessels_url notice: 'Vessel was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_vessel
      @vessel = Vessel.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def vessel_params
      params.require(:vessel).permit(:title, :description, :daily_price, :fee_pc)
    end
end

testapp/app/controllers/vessels_controller.rb
class VesselsController < ApplicationController
  before_action :set_vessel, only: [:show, :edit, :update, :destroy]

  # GET /vessels
  # GET /vessels.json
  def index
    @vessels = Vessel.all
  end

  # GET /vessels/new
  def new
    @vessel = Vessel.new
  end

  # GET /vessels/1/edit
  def edit
    @title = @vessel.title
    @description = @vessel.description
  end

  # POST /vessels
  # POST /vessels.json
  def create
    @vessel = Vessel.new(vessel_params)
    @ip = request.remote_ip
    respond_to do |format|
      if @vessel.save
        if (current_admin.nil?)
          NotificationMailer.new_post(@ip, @vessel).deliver_now()
        end
        format.html { redirect_to vessels_url, notice: 'Vessel was successfully created.' }
        format.json { render :show, status: :created, location: @vessel }
      else
        format.html { render :new }
        format.json { render json: @vessel.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /vessels/1
  # PATCH/PUT /vessels/1.json
  def update
    @ip = request.remote_ip
    @old_vessel = @vessel.as_json()
    respond_to do |format|
      if @vessel.update(vessel_params)
        @old_vessel["updated_at"] = @vessel.updated_at
        if (current_admin.nil?)
          NotificationMailer.edit_post(@ip, @vessel, @old_vessel, vessel_params).deliver_now()
        end
        format.html { redirect_to vessels_url, notice: 'Vessel was successfully updated.' }
        format.json { render :show, status: :ok, location: @vessel }
      else
        format.html { render :edit }
        format.json { render json: @vessel.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /vessels/1
  # DELETE /vessels/1.json
  def destroy
    @vessel.destroy
    respond_to do |format|
      format.html { redirect_to vessels_url, notice: 'Vessel was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_vessel
      @vessel = Vessel.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def vessel_params
      params.require(:vessel).permit(:title, :description, :daily_price, :fee_pc)
    end
end

testapp/app/helpers/admin/vessels_helper.rb
module Admin::VesselsHelper
end

testapp/app/helpers/vessels_helper.rb
module VesselsHelper
end

testapp/app/views/vessels/_form.html.erb
<%= form_for(@vessel) do |f| %>
  <% if @vessel.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@vessel.errors.count, "error") %> prohibited this vessel from being saved:</h2>

      <ul>
      <% @vessel.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <dl class='form-fields'>
    <dt><%= f.label :title, 'Title:' %></dt>
    <dd><%= f.text_field :title %></dd>

    <dt><%= f.label :description, 'Description:' %></dt>
    <dd><%= f.text_area :description %></dd>

    <dt><%= f.label :daily_price, 'Daily Price:' %></dt>
    <dd><%= f.text_field :daily_price %></dd>

    <dt><%= f.label :fee_pc, 'Fee %:' %></dt>
    <dd><%= f.text_field :fee_pc %></dd>
  </dl>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

testapp/app/views/vessels/edit.html.erb
<h1>Editing Vessel</h1>

<%= render 'form' %>

<%= link_to 'Back', vessels_path %>

testapp/app/views/vessels/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Vessels</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Daily price</th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% @vessels.each do |vessel| %>
      <tr>
        <td><%= vessel.title %></td>
        <td><%= number_to_currency(vessel.daily_price) %></td>
        <td><%= link_to 'Edit', edit_vessel_path(vessel) %></td>
        <td><%= link_to 'Destroy', vessel, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Vessel', new_vessel_path %>

testapp/app/views/vessels/new.html.erb
<h1>New Vessel</h1>

<%= render 'form' %>

<%= link_to 'Back', vessels_path %>