BookReview/config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :books do
  	resources :reviews
  end
  root 'books#index'
end

BookReview/app/models/book.rb
class Book < ActiveRecord::Base
	has_attached_file :book_img, styles: { book_index: "250x350>", book_show: "325x475>" }, default_url: "/images/:style/missing.png"
  	validates_attachment_content_type :book_img, content_type: /\Aimage\/.*\Z/
	belongs_to(:user)
	belongs_to(:category)
	has_many(:reviews)
end

BookReview/app/models/category.rb
class Category < ActiveRecord::Base
	has_many(:books)
end

BookReview/app/models/review.rb
class Review < ActiveRecord::Base
	belongs_to(:user)
	belongs_to(:book)
end

BookReview/app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
    has_many(:books)
    has_many(:reviews)
end

BookReview/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper_method :current_user 

	def current_user 
  		@current_user ||= User.find(session[:user_id]) if session[:user_id] 
	end

	def require_user 
  		redirect_to(new_session_path) unless current_user 
	end
end

BookReview/app/controllers/books_controller.rb
class BooksController < ApplicationController
	before_action(:find_book, only: [:show, :edit, :update, :destroy])

	def index
		if params[:category].blank?
			@books = Book.all.order("created_at DESC")
		else
			@category_id = Category.find_by(name: params[:category]).id
			@books = Book.where(:category_id => @category_id).order("created_at DESC")
		end
	end

	def show
	end

	def new
		@book = current_user.books.build
		@categories = Category.all.map{|c| [c.name, c.id]}
	end

	def create
		@book = current_user.books.build(book_params)
		@book.category_id = params[:category_id]
		if @book.save
			redirect_to(root_path)
		else
			render('new')
		end
	end

	def edit
		@categories = Category.all.map{|c| [c.name, c.id]}
	end

	def update
		@book.category_id = params[:category_id]
		if @book.update(book_params)
			redirect_to(book_path(@book))
		else
			render('edit')
		end
	end

	def destroy
		@book.destroy()
		redirect_to(root_path)
	end

	private
	def book_params
		params.require(:book).permit(:title, :description, :author, :category_id, :book_img)
	end

	def find_book
		@book = Book.find(params[:id])
	end
end

BookReview/app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
	before_action :find_book
	before_action :find_review, only: [:edit, :update, :destroy]

	def new
		@review = Review.new
	end

	def create
		@review = Review.new(review_params)
		@review.book_id = @book.id
		@review.user_id = current_user.id

		if @review.save
			redirect_to(book_path(@book))
		else
			render('new')
		end
	end

	def edit
	end

	def update
		if @review.update(review_params)
			redirect_to(book_path(@book))
		else
			render('edit')
		end
	end

	def destroy
		@review.destroy
		redirect_to(book_path(@book))
	end

	private
	def review_params
		params.require(:review).permit(:rating, :comment)
	end

	def find_book
		@book = Book.find(params[:book_id])
	end

	def find_review
		@review = Review.find(params[:id])
	end
end

BookReview/app/helpers/reviews_helper.rb
module ReviewsHelper
end

BookReview/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BookReview</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<nav class="navbar navbar-default">
	<div class="container">
		<div class="navbar-header">
			<%= link_to("Book Review", root_path, class: "navbar-brand")%>
		</div>
		<ul class="nav navbar-nav">
			<li><%= link_to("Sign Up", new_user_registration_path)%></li>
			<% if user_signed_in? %>
				<li><%= link_to("Sign Out", destroy_user_session_path, method: :delete)%></li>
			<% else %>
				<li><%= link_to("Log In", new_user_session_path)%></li>
			<% end %>
		</ul>
		<ul class="nav navbar-nav navbar-right">
			<li class="dropdown">
				<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Categories<span class="caret"></span></a>
				<ul class="dropdown-menu" role="menu">
					<% Category.all.each do |category|%>
						<li class="<%= 'active' if params[:category] == category.name %>">
							<%= link_to(category.name, books_path(category: category.name), class: "link") %>
						</li>
					<%end%>
				</ul>
			</li>
			<% if user_signed_in? %>
				<li><%= link_to("Add Book", new_book_path)%></li>
			<% end %>
		</ul>
	</div>
</nav>

<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

<div class="container">
	<%= yield %>
</div>

</body>
</html>